apiVersion: v1
kind: Service
metadata:
  name: livros-api-service 
spec: 
  type: ClusterIP
  selector:
    app: livros-api
  ports:
    - port: 80
      targetPort: 8000
      NodePort: 32489
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  
  